// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD230Wtx7yUYLWs7Q1ADnEz2JZtKF65Hv8',
    appId: '1:254610665510:web:67151cff61ed37605df6e7',
    messagingSenderId: '254610665510',
    projectId: 'moontripe-bad71',
    authDomain: 'moontripe-bad71.firebaseapp.com',
    storageBucket: 'moontripe-bad71.firebasestorage.app',
    measurementId: 'G-XTGFNJ41PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4W7YxBurFzteiQLR-Rn0vx462OLbZm8s',
    appId: '1:254610665510:android:49f61dde1d7eecd45df6e7',
    messagingSenderId: '254610665510',
    projectId: 'moontripe-bad71',
    storageBucket: 'moontripe-bad71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXu6HYsd9n3Q0AAl7pgA_hBlaj-kZpJs0',
    appId: '1:254610665510:ios:e22189bb4ab068945df6e7',
    messagingSenderId: '254610665510',
    projectId: 'moontripe-bad71',
    storageBucket: 'moontripe-bad71.firebasestorage.app',
    iosBundleId: 'com.example.mobileapplicaion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXu6HYsd9n3Q0AAl7pgA_hBlaj-kZpJs0',
    appId: '1:254610665510:ios:e22189bb4ab068945df6e7',
    messagingSenderId: '254610665510',
    projectId: 'moontripe-bad71',
    storageBucket: 'moontripe-bad71.firebasestorage.app',
    iosBundleId: 'com.example.mobileapplicaion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD230Wtx7yUYLWs7Q1ADnEz2JZtKF65Hv8',
    appId: '1:254610665510:web:6592eb5830b756bd5df6e7',
    messagingSenderId: '254610665510',
    projectId: 'moontripe-bad71',
    authDomain: 'moontripe-bad71.firebaseapp.com',
    storageBucket: 'moontripe-bad71.firebasestorage.app',
    measurementId: 'G-R11S51105J',
  );
}
